// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://jerfstkniwyxnsnimcrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplcmZzdGtuaXd5eG5zbmltY3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjIwOTAsImV4cCI6MjA2NjMzODA5MH0.f8WGzacMcFXvZV_sMOjv2s1o8OoidFxUKgdgij0xUkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
